name: Provision GKE Cluster

on:
  pull_request:
    types: [labeled]

jobs:
  provision-GKE-Cluster:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'spin up environment')

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: Setup terraform
        run: |
          export VER="0.12.21"
          wget https://releases.hashicorp.com/terraform/${VER}/terraform_${VER}_linux_amd64.zip
          unzip terraform_${VER}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform version

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Run infrastructure script to provision GKE Cluster
        run: |
          chmod +x scripts/prov_infrastructure.sh
          bash ./scripts/prov_infrastructure.sh

  destroy-GKE-Cluster:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'destroy environment')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Destroy GKE Cluster
        if: success()
        run: |
          terraform destroy
